module.exports = {
    theme: {
        name: 'default',
        types: {
            feat: { title: 'Features' },
            perf: { title: 'Performance Improvements' },
            fix: { title: 'Bug Fixes' },
            refactor: { title: 'Code Refactoring' },
            docs: { title: 'ocumentation' },
            chore: { title: 'Chores' },
            build: { title: ' Build System' },
            test: { title: 'Tests' },
            types: { title: 'Types' },
            style: { title: 'Styles' },
            reverts: { title: 'Reverts' },
            deps: { title: 'Dependencies' },
            ci: { title: 'ontinuous Integration' },
            release: { title: 'release' },
            other: { title: 'Other' },
        },
    },
    showContributors: false,
    showNotMatchComiit:false,
    repository: 'https://github.com/alqmc/gacm',
};
